global:
  scrape_interval: 15s # Scrape targets every 15 seconds

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Scrape Prometheus itself

  - job_name: "node_exporter"
    static_configs:
      - targets: ["ip-172-31-40-218:9100"] # Scrape a Node Exporter